### ISSUE TITLE
Admin multiwallet whitelist + topwallet through the admin proxy contract

### ISSUE THREAD

**Issue by AlexeyKosinski** [GoodDollar/GoodServer#100]
Create AdminContractWallet that should have same functionality as AdminWallet
an env variable will decide which type of wallet to use

Definition of done
 - [ ] make whitelist + topwallet through the admin proxy contract so we dont need to make an admin and have funds in each wallet address, we will use a contract as a wallet. (see GoodDollar/GoodContracts#30 in godocontracts)

**Comment by sirpy** [comment]
issues with multiple txs on same block, see PR
