### ISSUE TITLE
Collect token information for dashboard to mongoDB

### ISSUE THREAD

**Issue by AlexeyKosinski** [GoodDollar/GoodServer#104]
- balances. 
    - top, low, median
    - distribution histogram - 10 buckets
    - show top 10 accounts
 - count of transactions
   - top, low, median
   - distribution
   - show top 10 accounts

Use web3 getPastEvents to collect this information from blockchain to mongo db

How:
- first time get all information from all blockchain blocks and save last `blockNumber` to DB
- next time get information from blockchain block starting from `blockNumber`
- get information from blockchain every REFRESH_INTERVAL minutes
- add REFRESH_INTERVAL to env

Definition of done:
- [x] create init function which gets all data from blockchain 
- [x] add refresh information by interval function
- [x] save info in mongodb: address, balance, count of tx

**Comment by sirpy** [comment]
@StanislavShevchenko @AlexeyKosinski need to use getPastEvents not allevents
