### ISSUE TITLE
Create wallet disappear if pressing back

### ISSUE THREAD

**Issue by tzvister** [GoodDollar/GoodServer#118]
Found what I think is a bug:
1. As a new user without an Wallet, after I've signed up for Web3
2. From Web3 dashboard, go to "Go to my wallet"
3. The correct two buttons "Create Wallet" and "Sign-in" shows up.
4. Assuming I do not have a Wallet, a user is expected to choose "Create Wallet" - However!

4.1 If the user chooses "Sign-in" by mistake, they get the sign-in screen.
4.2 The user realised they do not have a way to Sign-In, so they click "Back"

5. The option for "Create Wallet" disappears, and the user is sent the "Get invited" button instead.

The user is confused and lost :(

Cause
---
in signin and in mnemonics we perform
AsyncStorage.removeItem('GD_web3Token')
this should be delayed to the last possible moment

Definition of Done
- [ ] w3 user with token should be able to go back if mistakingly went to signin/mnemonics recovery

**Comment by sirpy** [comment]
@LiavGut hmm maybe should only create wallet if from web3? or start directly in the signup process if from web3

**Comment by LiavGut** [comment]
@sirpy 
What if a user comes via payment link and doesn't have a wallet?

By clicking "create a wallet" a user is accepting our TOU and our PP, so we'll need to change it or maybe create a special welcome screen from web3

**Comment by sirpy** [comment]
@LiavGut ping

**Comment by sirpy** [comment]
@Talbatz i couldnt recreate this

**Comment by sirpy** [comment]
@StanislavShevchenko this is replaced by #981
