### ISSUE TITLE
user was created without details

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodServer#119]
on ewallet user with identifier 0x7fdd8d72b3efba8022a8456ac1a18dda8b4964f8
was saved with no data in privatedb
try to figure out how is it possible in /user/add
ask @LiavGut for his wallet key to further investigate

How:
1. in user/add function save each successful step into mongo db
2. before run each step check om mongo if it is already done not run it

**Comment by StanislavShevchenko** [comment]
@sirpy 
You can skip the dead / add step. If you copy the mnemonics and go to the site through the recovery page

**Comment by AlexeyKosinski** [comment]
to fix this issue I think we need to finish this first https://app.zenhub.com/workspaces/gooddollar-5d50833888a83c6880d3e345/issues/gooddollar/gooddapp/935
@sirpy

**Comment by AlexeyKosinski** [comment]
update ticket description
