### ISSUE TITLE
switch logger from pino

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodServer#126]
pino doesnt allow to override the .error method
so we cant send errors also to 3rd apis

find a different logger, maybe winston?

**Comment by yaroslav-fedyshyn-nordwhale** [comment]
@sirpy I found the way to extend the error method of pino logger. Working with child loggers too.
You can find the implementation in this PR https://github.com/GoodDollar/GoodDAPP/pull/1055 (commit - https://github.com/GoodDollar/GoodDAPP/pull/1055/commits/86e365e5a588d905f625b1ca0fec7fdfbf7749f6).

**Comment by sirpy** [comment]
@AlexeyKosinski @yaroslav-fedyshyn-nordwhale this is a GoodServer issue.
on client it we already overwrite the error logging in analytics.js, update your GoodDAPP PR.
but regardless the issue is on server.
