### ISSUE TITLE
user not able to create account after failure

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodServer#133]
User creation failed for me on generateMarketToken (/user/add)
when pressing on lets start again server fails again but this time with error that you can't create account with same credentials.

issue seem to be the createddate which is added in the begining of signup process and not when user finish

**Comment by yaroslav-fedyshyn-nordwhale** [comment]
@sirpy so the solution is to update the mongo userRecord with dateCreated at the end of POST /add/user fn handler.

**Comment by sirpy** [comment]
ok try it

**Comment by sirpy** [comment]
@AlexeyKosinski does this solves #935?
