### ISSUE TITLE
web3 user registration should accept invite token from goodserver

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodServer#156]
Currently Goodserver can register users to web3 by calling
HTTP PUT /api/wl/user
with the following json
```
{
email: user.email,
        full_name: user.fullName,
        wallet_address: user.gdAddress,
       inviter: {id: <code>}

}
```
it should also accept an invite token/code and mark correctly on web3 who invited the user

Definition of Done
-  web3 api accepts inviter on  /api/wl/user
- web3 updates correctly the invitation model according to the inviter

**Comment by sirpy** [comment]
@Sergezdv this is what you should work on.
Please use the zenhub board. you should check backlog issues. icebox are not relevant.

**Comment by sirpy** [comment]
@Sergezdv looking at the code I see the the basic format is for 
`
{inviter: {id: code}}
`
we can keep it

**Comment by Sergezdv** [comment]
@sirpy
to indicate the inviter - the `invite_code` parameter should be passed
API endpoint:
`PUT /api/wl/user`, params: 
```
secure_hash = md5(email + SECURE_KEY);
invite_code = inviter.invite_code
params: {
  secure_hash,
  email,
  full_name,
  wallet_address,
  invite_code?,
  approved?(bool),
  image?(url),
}
```
http://joxi.ru/xAeGL5ZTgPZxpm.jpg

**Comment by sirpy** [comment]
@Sergezdv  ok 10x.
please move issues to Review when done.
also point to PR/relevant commit hashes in the web3 code

**Comment by Sergezdv** [comment]
@sirpy it was provided and added earlier, so that it did not require additional changes in the code
