### ISSUE TITLE
Enhance enrollment logic

### ISSUE THREAD

**Issue by serdiukov-o-nordwhale** [GoodDollar/GoodServer#166]
1. We could remove liveness check as it also performed by enrollment endpoint

[x] remove liveness check method from Zoom API wrapper
[x] remove extra liveness check from ZoomProvider. Should be check duplicate then enroll
[x] remove related unit tests & test helpers
[x] move failure reasons tests (e.g. waring, glasses, poor quality etc) to the enrollment test cases
[x] mock failed duplicates search instead of liveness in the ZoomProvider / ResponseProcessor / verificationAPI tests

2. [x] if user.isVerified we need to make sure to whitelist him, maybe we changed the whitelisting contract and he is no longer whitelisted there, so we trust that we already whitelistedhim in the past and whitelist him again in the new contract

3. [x] explain better in comments how is already enrolled is passed from the thrown exception
4. [x] remove duplicate's identifier from error message

**Comment by serdiukov-o-nordwhale** [comment]
@sirpy Actually, `alreadyEnrolled` isn't passed from the thrown exception

We're throwing exception if code **non-equals** `nameCollision` , e.g. **in other cases ** that 'already enrolled'

After this `if` block we have logic for 'already enrolled' case - we're setting corresponding flag, and the last API response. Then we're exiting `catch` block going further where we're returning enrollment result with the lastest response and all status flags (including `alreadyEnrolled`)

I've updated comments with more detailed logic explanation

**Comment by sirpy** [comment]
@serdiukov-o-nordwhale ok

**Comment by sirpy** [comment]
1. if response.data is empty then you will not merge "meta" to the the response
2. you dont actually use the merged zoomResponse, so i think places where you expect to read data from meta will not work (ie enrollmentExists)
3. why do you delete exception.response? no reason to delete it
4. add  log.debug to print zoom responses, log.info in key places in  verification process. pass the log down from req. so we can trace all logs to a single call.

**Comment by serdiukov-o-nordwhale** [comment]
Found issue why enrollment removal won't work.
Fore remove enrollment with id `fake-enrollment-identifier` we should call
```
DELETE /enrollment/fake-enrollment-identifier
```
but actually we're calling
```
 {"url":"/enrollment/:enrollmentIdentifier","method":"delete","params":{"enrollmentIdentifier":"fake-enrollment-identifier"}
```

Substituting params to the uri isn't working (it wasn't covered by the tests and we've used before uri without params - e.g. POST /search|enrollment|liveness)
Now this case is covered and i'll fixing it right now

**Comment by serdiukov-o-nordwhale** [comment]
found reason why enrollments won't be removed 
in request interceptor i added params to url substitution

e.g. axios.delete('/enrollment/:id', { params: {id: 123}}) should actually do axios.delete('/enrollment/123')

but i've failed in the matching regex.
now it's ok and i've covered this in the tests
