### ISSUE TITLE
Enable faceverification on gooddev

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodServer#169]
- [x] enable on gooddev
- [x] delete account on dev should immediatly delete the face record

**Comment by serdiukov-o-nordwhale** [comment]
- env vars was updated on Heroku & Netlify
- added ability to remove face records immediately on account removal.  (to set  KEEP_FACE_VERIFICATION_RECORDS=0)
- enabled immediate face records removal on gooddev & goodqa
- FR is ready for deploy

**Comment by serdiukov-o-nordwhale** [comment]
committed to master
