### ISSUE TITLE
Server should have a claim queue

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodServer#174]
- [x] number of open places read from env
- [x] keep track of total whitelisted users and total queued
- [x] endpoint to add user to queue or get his status
   - [x] if open spaces or user already in queue then do nothing
   - [x] add to user record `{ claimQueue: { date: <dateadded>, status: 'pending|approved|whitelisted'}}`
   - [x] tag user in mautic `inClaimQueue`
   - [x] returns ok:0 if user exists/or already verified, returns ok:1 if user was added to queue or approved immediatly
- [x] once user is whitelisted after FR, remove his mautic tag or add tag 'whitelisted'
- [x] only 'approved' user can perform face verification

**Comment by tomerGD** [comment]
- Don't release this ticket to the production, wait for phase 1 official launch. 
@sirpy
