### ISSUE TITLE
Update mautic contact when user udpates email/mobile

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodServer#178]
in /verify/email and /verify/mobile
need to also update mautic contact

**Comment by iLystopad** [comment]
@sirpy The email/phone number is updated in the Mautic after editing ones on the My Profile screen.

Checked on the QA 1.24.1-6
Device: Desktop / Windows 10 / Google Chrome  89.0.4389.90

Attachment: https://www.screencast.com/t/Km1oobeGDf5
