### ISSUE TITLE
mark mautic user with tags for the queue stages

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodServer#197]
also tag user
- [ ] claimqueue_in  - user added to queue
- [ ] claimqueue_autoapproved - user approved to claim immediatly, without being added to queue first (when there are open spaces)
- [ ] claimqueue_claimed - user passed FV

**Comment by iLystopad** [comment]
@sirpy The user is added to the Claim Queue Whitelisted segment and marked by the tag claimqueue_claimed after passing the FV.

Checked on the Prod 1.25.0
Device: Desktop / Windows 10 / Google Chrome 89.0.4389.90

Attachment: 
![image.png](https://images.zenhubusercontent.com/5fe99267688d8a03d64eabd2/5d79b3ff-606a-4c34-ba99-2f798b18366c)
