### ISSUE TITLE
(Bug) duplicate log of variables

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodServer#211]
the logger prints duplicate data to console
it adds a "context" variable which duplicates existing variables
example:
`2020-07-19T10:49:24.736Z - info (FROM GunDB-Middleware ): {"name":"publicdb","message":"Authenticated GunDB user:","context":[{"name":"publicdb"}]}`

**Comment by serdiukov-o-nordwhale** [comment]
it's fixed during fixing 'duplicated context' issue
