### ISSUE TITLE
(bug) express depracted syntax crashes  logs

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodServer#231]
there was an express depracted syntax exception in OTP verificaiton, after it happened logging stopped working but seems like server continued to function
- [x] do we catch such exceptions? and handle them correctly? so server can recover?
- [x] why logs stop?

**Comment by serdiukov-o-nordwhale** [comment]
Express uses `depd` package to print deprecation warnings
It prints it directly to the stderr. Probably this some could break winston's output (some handle/resource become locked and winston couldn't print).

We could avoid this by adding process.on('deprecation') listener. In this case depd won't print deprecation messages directly to the stderr, it allows custom listeners to do what they want with the deprecation error. I've just added logging as generic error (e.g. log.error('label', e.message, e))

**Comment by serdiukov-o-nordwhale** [comment]
Also i've added logger monitor which logs all global error events (e.g. uncaught errors, unhandled promises, warnings etc)
