### ISSUE TITLE
Unify errors processing - server side

### ISSUE THREAD

**Issue by serdiukov-o-nordwhale** [GoodDollar/GoodServer#239]
- [ ] throw only JS Error objects
- [ ] add metadata to the errors received from http calls
- [ ] add metadata to the errors received from the GUN
- [ ] add metadata to the errors received from the wallet methods
- [ ]  add any other metadata in the cases where it's needed

for more info please see https://app.zenhub.com/workspaces/gooddollar-5d50833888a83c6880d3e345/issues/gooddollar/gooddapp/2354

**Comment by johnsmith-gooddollar** [comment]
done
