### ISSUE TITLE
reduce error logs in server

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodServer#312]
- [x] faceverification regular issues such as duplicate/liveness should be warn only. only unexpected issues should be log error
- [ ] go over log.error discuss which can be reduced to warn
- [ ] pass request logger to admiinwallet calls

**Comment by serdiukov-o-nordwhale** [comment]
Also some success messages are added to the monitoring alerts:

```
MonitoringAlertsAPP  7:13 AM
{"msg":"success: UBI transfered","ubiTransfered":"843798296","env":"development","version":"1.20.1-1","network":"fuse"}
```

@sirpy is this ok ? probably you added an alert for that particular event (ubi transferred) ?

**Comment by sirpy** [comment]
yes thats fine
