### ISSUE TITLE
update backend to work with protocol v2

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodServer#327]
- new contracts from @gooddollar/goodprotocol
- fish from new ubi
- feature toggle based on env
- fake interest for dev/qa envs

**Comment by vldkh** [comment]
@sirpy 
After creating a new account via the invite link - there are a lot of similar errors appear.

Environment:
QA 1.30.1-8

Devices:
Windows 10 // Google Chrome v92 

Attachments:
https://www.screencast.com/t/jUX6zKIRDJf

**Comment by sirpy** [comment]
@vldkh please retest

**Comment by vldkh** [comment]
@sirpy @lukasz-kilaszewski @johnsmith-gooddollar 
checked via #3326
