### ISSUE TITLE
Log SMS verification requests to twilio on Amplitude so we can monitor and alert over-usage

### ISSUE THREAD

**Issue by tzvister** [GoodDollar/GoodServer#330]

**Comment by tzvister** [comment]
I think we didn’t set up the new Twillio event fire well, it seems like we’re exeeding number of “Properties” for the event, which suggest that the properties being sent to the event aren’t set up right

![Screenshot 2021-08-11 at 14.52.14.png](https://images.zenhubusercontent.com/5d6d33bc0160a505af4b5b22/b74481a3-7ec1-41a2-a0e9-00e283ce5a38)

**Comment by tzvister** [comment]
ok, @sirpy says this was fixed.

**Comment by vldkh** [comment]
@tzvister 
now it is possible to monitor and alert over-usage

**Attachments:**
https://www.screencast.com/t/6AmlB5fe9d
