### ISSUE TITLE
Recovery email is not resolving {seed} variable

### ISSUE THREAD

**Issue by pablofullana** [GoodDollar/GoodServer#34]
### Description
Recovery email is not resolving `{seed}` variable

### Steps to reproduce
1. Register
1. Wait for email

### Supporting data
![Image 2019-05-27 at 5 52 01 PM](https://user-images.githubusercontent.com/1939415/58439001-5aef3d00-80a8-11e9-9f4c-00a4b2f0622f.png)

**Comment by sirpy** [comment]
fixed by fixing mautic template
