### ISSUE TITLE
Migrate Mautic API to Ongage API

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodServer#351]
- [x] contact creation/update should be done via ongage
- [x] events should be sent to ongage
- [x] wallet events that are sent to mautic (currently just last claim) should be sent to ongage.
- [ ] ~can we use this oppurtunity to move some server endpoints to vercel?~

### To Test
- [x] the moment we have user email, his details are sent to ongage (wallet calls server /user/start endpoint)
- [x] once user finishes registration his details are updated and a has a field signup_completed=true
- [x] when user verify a new mobile it is changed on ongage
- [x] when user verify a new email it is updated on  ongage
- [x] when user passes face verification he should have field whitelisted=true
- [x] when user delete account it should also be deleted from ongage
- [x] when user claims his last_claim and claim_counter should be updated on ongage

**Comment by sirpy** [comment]
@vldkh this would need to be test on QA. see list of things to test.

@johnsmith-gooddollar this should not be deployed to production until we updated our user db with the new ongage record ids

**Comment by vldkh** [comment]
@johnsmith-gooddollar 
 'Whitelisted' and 'firstClaim' params didn't set on Ongage
[https://app.zenhub.com/files/165812629/888ef709-b7ba-4c7c-bab4-61de33618c01/download](https://app.zenhub.com/files/165812629/888ef709-b7ba-4c7c-bab4-61de33618c01/download)

**Comment by johnsmith-gooddollar** [comment]
@vldkh 

1. where did you found this message ''Whitelisted' and 'firstClaim' params didn't set on Ongage' ?
2. if it's something needs to be set up on the CRM side please give me creds or ask @sirpy to do it
3. by the logic setWhitelisted sends only { whitelisted: 'true' }. True as the string not as the boolean value. This was implemented initially by @sirpy i've left this untouched

**Comment by johnsmith-gooddollar** [comment]
@vldkh yes, the user have crmId == null
```
{"whiteList":false,"topWallet":false},"isEmailConfirmed":true,"regMethod":"torus","torusProvider":"google","walletAddress":"0x73a3444055a2affdb530c5b5d532723a9efb7b4a6a6ef4df7b0e444b65ee9f29","createdDate":"2022-02-23T14:36:42.000Z","crmId":null}}]}[39m
```

Does this account is newly created or it was existing  ?
I checked the code and it don't seems  we have some update script for existing users to set crm id for them.
I need to switch to the feed, will continue research next Monday

**Comment by johnsmith-gooddollar** [comment]
@vldkh It seems the account was created before OnGage release. I wasn't able to find any logs regarding `createCRMRecord` calls. Could you please create new acc from scratch and check FV on it

@sirpy where we could add  ongage migration ? could i add it to `scripts/dbUpdates` ?

**Comment by johnsmith-gooddollar** [comment]
@vldkh thanks for the logs, will check tomorrow

**Comment by johnsmith-gooddollar** [comment]
found the issue. there's no complete v2 API, just 2 endpoints (v2/contacts and v2/change_status).
i've set base URL to just '/api' and added v2 prefix for those particular calls
now v2 is used for add contact so we have the correct response format
v1 add conact had different format so we weren't able to parse it correctly and got crmId == null

**Comment by vldkh** [comment]
@johnsmith-gooddollar 
According to the Ongage:
1) the 'Whitelisted' works fine, after passing the FV 'Whitelisted' parameter set 'true'
2) the 'LastClaim' parameter didn't set on Ongage, need to check logs on the server

**Comment by johnsmith-gooddollar** [comment]
Having strange issue with validation. 
the data seems to be ok (i compared with set whitelisted field request) but we're getting 412 error
I've adjusted request to use email as the key field on update too (if it's set)

Will continue research this evening or tomorrow

**Comment by johnsmith-gooddollar** [comment]
@vldkh is able to make quick test via mobile internet. waiting for the new logs
