### ISSUE TITLE
(Bug) ongage email change fails

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodServer#360]
search in logs for `Request failed with status code 404`
some failed because email is the same just different case, thats ok, already fixed.
other email changes failed
- [x] why did they fail?
- [x] what happens if new email already exists in a different contact? how do we handle this? does it merge?

**Comment by johnsmith-gooddollar** [comment]
@sirpy 

> why did they fail?

**PUT** `/api/contacts/change_email` had to be used, instead of **POST**.

**Comment by johnsmith-gooddollar** [comment]
hotfixed: https://github.com/GoodDollar/GoodServer/commit/dfffaaf96d963d9ad79a8df358fec38f5896ce73

**Comment by johnsmith-gooddollar** [comment]
@sirpy  fields `source_utm` `medium_utm` had been added

**Comment by johnsmith-gooddollar** [comment]
@sirpy. Regarding point 2 - if try to set email from the other existing contact it fails:

![image.png](https://images.zenhubusercontent.com/6135d0416eed5f7809f4ee6b/f5901770-bc7d-4e70-878d-3df6d68ba076)

Se we need to process this case separately
- check by_email for new email existense
- if exists - delete existing contact

**Comment by johnsmith-gooddollar** [comment]
hotfixed: https://github.com/GoodDollar/GoodServer/commit/539ae2a3409013b0aba88c6f5154260d3d3db844

**Comment by johnsmith-gooddollar** [comment]
tested, pushed to PROD

**Comment by sirpy** [comment]
@johnsmith-gooddollar we need to take care of other accounts with the crmId you deleted.
so that means that if another account exists already, then we should either
1. simply modify the user crmId to the existing one and deleting his current crmId
2. or search in our database for the user with the deleted crmId and switch it to the current user crmId

**Comment by sirpy** [comment]
yes users should share same crmId. no it is not defined unique

**Comment by johnsmith-gooddollar** [comment]
@sirpy done, tested on QA, hotfixed to prod
