### ISSUE TITLE
(Bug) ongage errors

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodServer#364]
### Description
Looking at the logs (regex /OnGage error/), we have two repeating errors
- 3000ms timeout
- request failed with 404, they all have the same pattern of failing to call the by_email endpoint with %40 instead of @ `{"url":"contacts/by_email/rizkypinong93%40gmail.com"}]}`

### Todo
- [x] Increase timeout and/or add retry (timeout already increased on master, need to deploy)
- [x] examine why that call fails

**Comment by johnsmith-gooddollar** [comment]
1. added retry to OnGage calls:
https://github.com/GoodDollar/GoodServer/commit/e43eeffb70d62141e3705bab8ad814030f746cf0
2. calls failing with 404 are existence or duplicates checks:
https://github.com/GoodDollar/GoodServer/blob/master/src/server/crm/ongage.js#L134
https://github.com/GoodDollar/GoodServer/blob/master/src/server/crm/ongage.js#L85

**Comment by sirpy** [comment]
@johnsmith-gooddollar 
1. you didnt explain why the call fails. why does getting user by email throws an exception?
2. and? does it hurt current logic? is it ok that it throws an exception where it does?

**Comment by sirpy** [comment]
@johnsmith-gooddollar that retry commit is pretty big, did you test things?

**Comment by sirpy** [comment]
@johnsmith-gooddollar examine the 404 errors and trace why they happen and suggest fix

**Comment by johnsmith-gooddollar** [comment]
> @johnsmith-gooddollar examine the 404 errors and trace why they happen and suggest fix

I already examined
Those errors are ok they are parts of our logic (see my comment above)

To determine if some email exists/users we're doing call get by email
If it fails with 404 - that means no email exists/email not used

I've linked exact place in the code containing this logic 

Logging comes from crm api class which logs any success/failed intake response

**Comment by sirpy** [comment]
@johnsmith-gooddollar from what i see the logic is incorrect
L85 you marked expect a duplicateid to be falsy if no such user exists, instead it throws an exception and then the rest of the code after line l85 doesnt execute

**Comment by sirpy** [comment]
@johnsmith-gooddollar what about the refactor you did... did you verify things are working? can you push it to production?

**Comment by johnsmith-gooddollar** [comment]
> @johnsmith-gooddollar what about the refactor you did... did you verify things are working? can you push it to production?

1. I've tsted locally
2. @vldkh is performing QA check now
3. I'll also add unit test for retry case today

**Comment by johnsmith-gooddollar** [comment]
@sirpy 

a) it was tested on QA, everything is fine
b) i've just added unit test for retry case, found one issue happening after retry, fixed it, pushed to master and staging
https://github.com/GoodDollar/GoodServer/commit/c3f4cb94cbcfef6e2ba44dea57ffe93871ff7db2

Now we could push to PROD (with the wallet release)
