### ISSUE TITLE
email verification broken after mongodb upgrade

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodServer#401]
email verificaiton for new users seems to be broken.
it looks like the "otp" field that should temporarily hold the email address is no longer working as expected
- it contains a value of `{_id:<number>}` instead of `{email:<string>}`
- This points that mongodb is saving the otp field as a separate document.
- Also the schema for the OTP field seems old/incorrect could this have some effect on this?
- Was new user signup tested??

**Comment by johnsmith-gooddollar** [comment]
@sirpy yes I've asked @vldkhh to test **everything** related to profiles (signing / signup different methods, updating feed, updating profile etc)

**Comment by johnsmith-gooddollar** [comment]
@vldkhh Need to re-check it at QA & PROD.

- SMS pwdlress **signup** should work now.
- An OTP code should be sent after you enter email
- Code validation form should be submitted without errors
- registration should finish successfully

**Comment by vldkhh** [comment]
@johnsmith-gooddollar verified on PROD, works without errors
