### ISSUE TITLE
Deployment issue: Your slug size (405 MB) exceeds our soft limit (300 MB) which may affect boot time.

### ISSUE THREAD

**Issue by johnsmith-gooddollar** [GoodDollar/GoodServer#457]
This causes app to load slowly and don't pass 30 sec timeout for start listening the port

1. Is there a way to raise this timeout ?
2. Try to shrink the "slug" (whole app archived with the node modules). 
a) to check up which packages do we need which don't and
b) try to move some packages to devDeps. 
c) try https://github.com/heroku/heroku-repo?tab=readme-ov-file#gc
d) try .slugignore https://devcenter.heroku.com/articles/slug-compiler#ignoring-files-with-slugignore

**Comment by johnsmith-gooddollar** [comment]
The latest one working commit (without veramo) already have  288MB, so we're already "on the edge" so the issue should we solved. We would meet with it anyway in the near future even if didn't added veramo right now

**Comment by johnsmith-gooddollar** [comment]
@sirpy after my fix https://github.com/GoodDollar/GoodServer/commit/330e2d424926a297d0cd42ca8b936d2454490706 the slug size is 400MB again (

**Comment by sirpy** [comment]
@johnsmith-gooddollar i've changed webpack to not use nodeexternals for production, now it creates a single file and we can delete node_modules.
slug size is now 50mb on dev server
please verify that the credential endpoints are working as expected (ie the dynamic imports)

**Comment by sirpy** [comment]
solved by using compile to single file
