### ISSUE TITLE
[GoodID]: Fix redtent campaign criteria checks

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodServer#472]
### Description
We originally thought the campaign was only for Nigerian women.
The criteria that we know so far are:
1. Nigerian women
2. Colombian women

Pending Criteria:
- [ ] Philipines

Some fixes are needed to align with the expected criteria. Plus making sure the user is registered for the right pool

### Technical implementation
- [x] Fix the api-endpoint checks to accommodate to the criteria: https://github.com/GoodDollar/GoodServer/blob/3a8d5ed8ee72f3bdee035a2447dab8154d40e3bb/src/server/goodid/goodid-middleware.js#L332
- [x] Implement the registration of a valid submission/participant into the designated ubi pool: https://github.com/GoodDollar/GoodServer/blob/3a8d5ed8ee72f3bdee035a2447dab8154d40e3bb/src/server/blockchain/MultiWallet.js#L136

**Comment by L03TJ3** [comment]
@decentralauren I have assigned you, could you give us a final thumbs-up on all the confirmed countries?

**Comment by L03TJ3** [comment]
@decentralauren Could you give an update on the which pools we can expect?

**Comment by decentralauren** [comment]
@L03TJ3 there should be 3 live pools after the red tent UBI launches:
- Silvi pool
- Red Tent - Women in Nigeria
- Red Tent - Women in Colombia

For the latter 2 I'll have to share the pool detail page info (description, socials etc).

**Comment by L03TJ3** [comment]
@decentralauren okay, let me know when those details are available!
(fyi: this is for the server and managing registration of users into ubi-pools, silvi is not relevant here)

**Comment by sirpy** [comment]
@L03TJ3 
i've implemented this for dev env.
These are the dev env pools
```{"NG":"0x77253761353271813c1acA275De8eEC768B217C5","CO":"0x627dBf00cE1A54067f5a34d6596A217a029c1532"}```
The backend will register the user given the correct credentials.

**Comment by sirpy** [comment]
@L03TJ3 work with vlad to test it

**Comment by vldkhh** [comment]
@L03TJ3 could be closed?
