### ISSUE TITLE
'Zoom verification failed' - need to update Server SDKs

### ISSUE THREAD

**Issue by vldkhh** [GoodDollar/GoodServer#474]
Zoom verification failed on dev.

`'Zoom verification failed' 'You are attempting to use a 3D FaceScan that was generated with a newer version of the Device SDKs than the Server SDK you are using.  Please update your FaceTec Server SDK in order to resolve this issue.  For more information, please see https://dev.facetec.com/release-practices.' `

![image](https://github.com/user-attachments/assets/b2a8a53e-4c20-4ece-85e6-233136d3079f)

**Comment by decentralauren** [comment]
@vldkhh please test in prod.

**Comment by sirpy** [comment]
this is already working @vldkhh @decentralauren
