### ISSUE TITLE
Segmented UBI Pool updates

### ISSUE THREAD

**Issue by decentralauren** [GoodDollar/GoodServer#483]
Decisions for Red Tent pool design:
- Set a min and max amount for a set claim (min should be 1 G$ and max temporarily be at 8 G$, we will raise once we launch based on G$ price).
- Keep at max 500 addresses / claimers registered (we will monitor to see if we should take the alternate approach of 500 daily claimers)

Updates to contract design / parameters:
- Add configurable admin fee, default to 2%
- Add min claim amount for both types below
- 2 Distribution logic options:
--Fixed amount per day
--Automatic: 
--- cycleLengthDays: set to 30 days by default, configurable
--- Make cycle configurable (default to 14 days as current UBI contract) 
--- Add Min Amount - to avoid a long tail of transactions and a crazy gas situation 
--- Max Amount - to manage the # of pool members

**Comment by L03TJ3** [comment]
@decentralauren @sirpy please update status for this ticket, or close if everything is done
