### ISSUE TITLE
Seed phrase+magic link emails should be sent via sendgrid

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodServer#53]
Currently we use mautic to send seed phrase

Definition of Done
--
- mautic template is converted to sendgrid template
- recovery email is sent via sendgrid
- magic link email is sent via sendgrid

**Comment by kbardi** [comment]
@sirpy Could you give us access to Sendgrid and Mautic to make those changes please?

**Comment by sirpy** [comment]
@Talbatz can you create kevin mautic account+token for whatever email service we use?

**Comment by Talbatz** [comment]
We got a mailgun account and amazon SES. I assume we should get started
with mailgun (since it's far more informative) and later on we can always
move it to SES.

**Comment by kbardi** [comment]
Thanks @sirpy @Talbatz

**Comment by kbardi** [comment]
Paused until confirmation about what is the expected change...right now I have Mailgun api key and Mautic credentials, but nothing about Sendgrid, and the issue ask for a migration to Sendgrid...and also I have no access to Mailgun (not sure if I can create templated there) and I don't know if I should create HTML template directly on our server API
