### ISSUE TITLE
User facial record should be delete only after 24hours

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodServer#56]
Prevent fraud where user can claim, send GD to a different account and then delete his account and register again and claim again.

Once a user deletes his account we don't delete his facial identifier for 24Hours, so if he tries to Claim again he's going to fail the facial verification process

Definition of Done
--
- [x] when user delete accounts his Zoom identifier added to private db collection ({identifier,date})
- [x] only on production
- [x] interval task is running every hour to delete identifiers that passed 24hours
- [x] need to sync between different backend trying to delete the same identifier (maybe use findAndModify)
- [x] A user deletes his account and can register once more, but cannot claim GD for 24 hours from last Claim

**Comment by serdiukov-o-nordwhale** [comment]
@StanislavShevchenko please, see the following commit:
https://github.com/GoodDollar/GoodServer/pull/160/commits/9c0b3c83358cd1ced200610d977201a0db41b6e0

You'll find all instructions you needs to implement this task inside // TODO: comments

**Comment by serdiukov-o-nordwhale** [comment]
1. Define DisposeEnrollmentsTask's `name` as constant in the EnrollmentProcessor (will be user in the delayed tasks collection too) and re-use it by importing from EnrollmentProcessor
2. Create `DelayedTask` model in the `src/server/db/mongo/models`
{
  _id: ObjectID,
  userIdentifier: String,
  taskName: String // name (type, kind) of the delayed task. for 24h it should be ''verification/dispose_enrollments' (defined as constant),
  taskSubject: Any // some parameters (subject, options) of the task. Could be string number or object corresponding to the kind of the task. In our case it will be string with enrollmentIdentifier,
  running: Boolean // running flag to solve 'sync between different backend' issue
}

**Comment by serdiukov-o-nordwhale** [comment]
3. Add the following methods to the UserDBPrivate

async enqueueTask(userIdentifier: string, taskName: string, subject: any): Promise<DelayedTaskRecord>  

async fetchTasksForProcessing(taskName: string, filters: object = {}): Promise<DelayedTaskRecord[]> 
a) fetches task filtered by taskName + running !== true + conditions from filters parameter (in our case we'll use this param to pass 'createdAt is 24h ago or later' condition)
b) uses findAndModify to fetch records and immediately set running = true (to 'lock' tasks from the concurrent calls)

async unlockRunningTasks(tasksIdentifiers: string[]): Promise<void>
removes running flag using updateMany

**Comment by serdiukov-o-nordwhale** [comment]
4. In the addition to the EnrollmentProcessor's `disposeEnqueuedEnrollments` method comments:
- use fetchTasksForProcessing to get tasks
- instead p. 6
  a) call removeDelayedTasks for tasks succeeded
  b) call unlockRunningTasks for tasks failed
