### ISSUE TITLE
New user should get signup bonus

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodServer#75]
New user gets a signup bonus of 30 G$
We need to sync the case of user logging in from w3 or user created account directly on dapp

Definition of Done
- w3 gives signup bonus to users created via goodserver (sergey)

**Comment by sirpy** [comment]
@tzvister are we sure we want to give user signup bonus before he passes FaceVerification?

**Comment by Sergezdv** [comment]
@sirpy if there is no inviter (no invite_code in the request) then yes
if in the future an invit_code is added, then the sign_up bonus will also be awarded after approval by inviter

**Comment by sirpy** [comment]
@sergezdv
ok. thanks.
do the current w3 APIs we use in the wallet return the invite code of the
user?

**Comment by Sergezdv** [comment]
@sirpy no, but i can add

**Comment by sirpy** [comment]
@Sergezdv ok please do

**Comment by Sergezdv** [comment]
http://joxi.ru/a2XV4OjcwzXo0r.jpg
