### ISSUE TITLE
Adminwallet lock based on mutli-address

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodServer#88]
use the first X address from the mnemonic hdwallet
- [x]  adminwallet should be based on hdwallet (see client) and create X addresses
- [x] on startup verifies an entry exists in mongodb for each wallet address
- [x] when doing transaction find in mongodb first address that isn't locked and use that for transaction
- [ ] make whitelist + topwallet through the admin proxy contract so we dont need to make an admin and have funds in each wallet address, we will use a contract as a wallet. (see GoodDollar/GoodContracts#30 in godocontracts)

**Comment by sirpy** [comment]
@AlexeyKosinski see definition of done 4.

**Comment by AlexeyKosinski** [comment]
1. ok. good idea
2. but we need ether on each contract to run transaction.

**Comment by AlexeyKosinski** [comment]
need GoodDollar/GoodContracts#30 to continue

**Comment by sirpy** [comment]
@AlexeyKosinski if there is only 1 wallet with GD it will continue with 1 wallet right? so we don't need to wait for #30

**Comment by AlexeyKosinski** [comment]
yes we can set amount of wallets = 1. but now we generate  addresses with multi-wallet. so address can be changed. we can use one. but maybe we need to refill it and add it as admin wallet to contract

**Comment by sirpy** [comment]
@AlexeyKosinski i dont see the issue in your code you only use addresses that have >0 balance.
so our current code will run as usual without any need to change anything with just one address or am i missing something?

**Comment by AlexeyKosinski** [comment]
I've changed method of creating addresses from mnemonic. now it is like on frontend.
please see 
https://github.com/GoodDollar/GoodServer/pull/92/files
SoftwareWalletProvider
may be it will work. if adresses[0] will be the same as old admin address

**Comment by AlexeyKosinski** [comment]
tomorrow I will try with fuse network and let u know

**Comment by AlexeyKosinski** [comment]
regarding whitelist - create another task https://app.zenhub.com/workspaces/gooddollar-5d50833888a83c6880d3e345/issues/gooddollar/goodserver/100
